# Service Definition
version: "3.8" # Docker Compose 파일 형식 버전 (최신 권장)

services:
  nodejs-web: # 서비스 이름 정의
    restart: always # 컨테이너가 어떤 이유로든 종료되면 항상 재시작합니다.
    build: . # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드합니다.
    image: minah714/project2:latest # 빌드된 이미지를 minah714/project2:latest로 태그합니다.
    ports:
      - "3000:3000" # 호스트의 3000번 포트를 컨테이너의 3000번 포트에 매핑합니다.
    # 개발 중 코드 변경 시 즉시 반영을 위한 볼륨 마운트 (선택 사항, 프로덕션에서는 보통 사용 안 함)
    # volumes:
    #   - ./server.js:/usr/src/app/server.js
    #   - ./index.html:/usr/src/app/index.html
    #   - ./login.html:/usr/src/app/login.html
    #   - ./public:/usr/src/app/public # 정적 파일이 public 디렉토리에 있다면

