name: Python Streamlit APP
run-name: ${{ github.workflow }}

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Streamlit Server
        run: |
          nohup streamlit run streamlit3.py --server.port 8501 --server.headless true &
        timeout-minutes: 10

      - name: Stop Streamlit Server
        run: |
          pkill -f streamlit
